SRCNN_PATCH_SIZE = 96
SRCNN_STRIDE = 48

EDSR_PATCH_SIZE = 96
EDSR_STRIDE = 48
EDSR_SCALE_FACTOR = 2

ESRGAN_PATCH_SIZE = 96
ESRGAN_STRIDE = 48
ESRGAN_SCALE_FACTOR = 2

VGG_PATCH_SIZE = 96
VGG_STRIDE = 48

RANDOM_SEED = 42