SRCNN_PATCH_SIZE = 64
SRCNN_STRIDE = 32

EDSR_PATCH_SIZE = 48
EDSR_STRIDE = 24
EDSR_SCALE_FACTOR = 2

ESRGAN_PATCH_SIZE = 24
ESRGAN_STRIDE = 12
ESRGAN_SCALE_FACTOR = 2

VGG_PATCH_SIZE = 96
VGG_STRIDE = 48

RANDOM_SEED = 42